#ifndef EDITHELP_H
#define EDITHELP_H

void editor_help(void);

void editor_help_exit(void);
void editor_help_zoom_out(void);
void editor_help_save(void);
void editor_help_save_as(void);
void editor_help_open(void);
void editor_help_new(void);
void editor_help_save_and_play(void);
void editor_help_zoom_fill(void);
void editor_help_check_topology(void);
void editor_help_properties(void);
void editor_help_view_options(void);
// Toolok:
void editor_help_move(void);
void editor_help_zoom_in(void);
void editor_help_create_vertex(void);
void editor_help_delete_vertex(void);
void editor_help_delete_polygon(void);
void editor_help_create_food(void);
void editor_help_create_killer(void);
void editor_help_delete_object(void);
void editor_help_create_sprite(void);
void editor_help_delete_sprite(void);

#endif
